version: '3.8'

services:
  webserver1:
    image: httpd:latest
    container_name: roberts_httpd1
    ports:
      - "80:80"
    volumes:
      - roberts_vol1:/usr/local/apache2/htdocs/
    restart: unless-stopped
#    restart: on-failure:3
#    scale: 2
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/"]
#      interval: 1m30s
#      timeout: 30s
#      retries: 5
#      start_period: 30s
#  webserver2:
#    image: httpd:latest
#    container_name: roberts_httpd2
#    ports:
#      - "8080:80"
#    volumes:
#      - roberts_vol2:/usr/local/apache2/htdocs/
#    restart: unless-stopped
#    restart: on-failure:3
#    scale: 2
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/"]
#      interval: 1m30s
#      timeout: 30s
#      retries: 5
#      start_period: 30s
volumes:
  roberts_vol1:
#  roberts_vol2:
  
